#!/bin/sh
#-------------------------------------------------------------------------------------------------#
# AUTHOR:  Andrew Michaud - https://andrewmichaud.com                                             #
# FILE:    setup                                                                                  #
# PURPOSE: script to deploy config files and scripts in this repo.                                #
# UPDATED: 2016-06-22                                                                             #
# LICENSE: ISC                                                                                    #
#-------------------------------------------------------------------------------------------------#

# TODO This isn't quite rigorous enough in checking to be sure it's not trying to symlink files
# that already exist.
# Fix that.

#-------------------------------------------------------------------------------------------------#
###################################### GET XDG VARS ###############################################
#-------------------------------------------------------------------------------------------------#
echo "Determining necessary XDG env vars..."
echo

# Ensure vars are set.
OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
    DEFAULT_DATA="$HOME/Library"

elif [ "$OS" = "Linux" ]; then
    DEFAULT_DATA="$HOME/.local/share"

else
    echo "OS $OS currently unsupported!"
    exit 1
fi
XDG_DATA_HOME=${XDG_DATA_HOME-${DEFAULT_DATA}}
echo "XDG_DATA_HOME set to $XDG_DATA_HOME"

if [ -d "$XDG_DATA_HOME" ]; then
    if [ -L "$XDG_DATA_HOME" ]; then
        echo "Data DIR $XDG_DATA_HOME exists as a symlink."
    else
        echo "Data DIR $XDG_DATA_HOME exists as a directory."
    fi

else
    echo "Data DIR $XDG_DATA_HOME does not exist, creating."
    mkdir -p "$XDG_DATA_HOME"
fi

#-------------------------------------------------------------------------------------------------#
#################################### GET OTHER VARS ###############################################
#-------------------------------------------------------------------------------------------------#
echo
echo "Determining other necessary env vars..."
echo

# Get script/binary directory.
BIN_HOME="$XDG_DATA_HOME/bin"
echo "BIN_HOME set to $BIN_HOME"

# Ensure it exists.
if [ -d "$BIN_HOME" ]; then
    if [ -L "$BIN_HOME" ]; then
        echo "Bin DIR $BIN_HOME exists as a symlink."
    else
        echo "Bin DIR $BIN_HOME exists as a directory."
    fi

else
    echo "Bin DIR $BIN_HOME does not exist, creating."
    mkdir -p "$BIN_HOME"
fi

# Grab directory of git repo.
GIT_DIR="$(pwd -P)"
echo "GIT_DIR is $GIT_DIR"

# Grab places we'll put scripts and config files.
GIT_BIN_HOME="$GIT_DIR/bin"

#-------------------------------------------------------------------------------------------------#
##################################### DEPLOY SCRIPTS ##############################################
#-------------------------------------------------------------------------------------------------#
echo
echo "Deploying scripts..."
echo

# Deploy SCRIPTS.
echo "Linking all scripts in $GIT_BIN_HOME into $BIN_HOME"
SCRIPTS="$(find "$GIT_BIN_HOME" -maxdepth 1 -type f)"
for SCRIPT in $SCRIPTS; do
    SCRIPT_NAME="$(basename "$SCRIPT")"
    echo "On script $SCRIPT_NAME"
    if [ ! -L "$BIN_HOME/$SCRIPT_NAME" ]; then
        echo "Linking $SCRIPT into $BIN_HOME"
        ln -s "$SCRIPT" "$BIN_HOME"
    else
        echo "Found script $SCRIPT_NAME in $BIN_HOME already."
    fi
done
