#!/bin/sh

# Should be a newline-separated list of repo names without ".git".
list="$XDG_CONFIG_HOME/git/mirrored_repos"
fetch_command="git remote update"
git_dir="/home/git"

# Simple script to update mirrored git repos.
while read -r repo; do
    echo "CD-ing to ${git_dir}/${repo}.git"
    cd "${git_dir}/${repo}.git" || exit
    echo "Running $fetch_command"
    $fetch_command || break
done < "$list"
