#!/usr/bin/env python3

import os
import signal
import subprocess
import time

# Old script to get around weird MPD behavior on delete on OSX.

PLAYLIST = "pods"


def main():
    mpd_code = subprocess.run(
        ["pgrep", "-x", "mpd"],
        stdout=subprocess.PIPE,
        encoding="UTF-8",
    ).stdout.strip()

    if mpd_code != "":
        subprocess.run(["mpc", "pause"])
        subprocess.run(["mpc", "save", PLAYLIST])

        os.kill(int(mpd_code), signal.SIGTERM)

    home = os.path.expanduser("~")
    mpd_dir = os.path.join(home, "Library", "Caches", "mpd")

    files = list(map(lambda x: os.path.join(mpd_dir, x), ["database", "state", "sticker.sql"]))

    for file in files:
        if os.path.isfile(file):
            os.remove(file)

    subprocess.Popen("mpd")

    time.sleep(2)

    subprocess.run(["mpc", "load", PLAYLIST])
    subprocess.run(["mpc", "play"])


if __name__ == "__main__":
    main()
