#!/usr/bin/env python3
# Delete something in MPD and make sure the DB reflects that.

import argparse
import os
import subprocess
import time


def main():
    parser = argparse.ArgumentParser(
        description="safe delete files on disk and from MPD",
    )

    parser.add_argument(
        "FILE",
        help="a file to delete on disk and from MPD",
        nargs="+",
    )

    args = parser.parse_args()

    for file in args.FILE:
        print(f"Safe deleting {file}")
        os.remove(file)
        open(file, "w").close()
        time.sleep(2)
        subprocess.run(["mpc", "update"])
        time.sleep(2)
        os.remove(file)

if __name__ == "__main__":
    main()
